export const PRAY_TIME_ACTIONS = {
  RESET_PRAY_TIME: 'RESET',
  SET_CALC_METHODE: 'SET_CALC_METHODE',
  SET_INITIAL: 'SET_INITIAL',
  SET_LOCATION: 'SET_LOCATION',
  SET_NEXT_PRAYTIME: 'SET_NEXT_PRAYTIME',
};


export const THEME_ACTIONS = {
  RESET_THEME: 'RESET',
  SET_THEME: 'SET_THEME',
};

export default {
  ...PRAY_TIME_ACTIONS,
  ...THEME_ACTIONS,
};
